@echo off
title PYTHON SERVER in .bat file
color 2
echo you might delete serverTimeLog, serverTimeLog and README.txt files.
echo Unless they were generated by this app
echo Make sure you don't have them! They will be overwritten!
pause
cls
echo starting server
echo you have to have python installed on your computer for this script to work > README.txt
echo time:%time% date:%DATE% >> serverTimeLog.txt
echo %time% > serverIpData.txt
echo : >> serverIpData.txt
ipconfig >> serverIpData.txt

echo:
echo:
echo go to http://localhost:8000
start http://localhost:8000
cd %CD%
echo If you want to stop the server exit this screen
echo Also pressing (Ctrl+C) works (multiple times in this case to exit completely)
echo:
echo note... in serverIpData.txt you can see the ipconfig info just look for wifi (most likely) and look ipv4 address
echo within your LAN you can now get access to your server (files) 
echo at http://replaceWithYourIPv4Address:8000
echo for example your phone
echo:
color 6
python -m http.server 
color 1
cls
echo goodbye!

echo:
pause